download :
  folder :
    base : /Users/cederik/Documents/
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: downloader-in
      kafka:
        binder:
          brokers: localhost:29092